github.com:
    users:
        MihneaMoso:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: MihneaMoso
